/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.7.1/userguide/multi_project_builds.html
 */

rootProject.name = "spring-cloud"

include(
        "spring-utils",
        "spring-eureka",
        "spring-apigw",
        "photoapp",
        "spring-rabbitmq",
        "spring-kafka",
        "resilience4j",
        "resilience4j-server",
        "feignclient",
        "spring-config",
        "spring-config-consumer",
        "spring-admin",
        "spring-sleuth",
        "spring-vault")

